title: My Blog
description: Blog content management

collections:
  - title: Blog Posts
    name: blog
    folder: src/data/blog
    create: true
    fields:
      - name: title
        title: Title
        type: string
        required: true
      - name: author
        title: Author
        type: string
        required: true
      - name: pubDatetime
        title: Publication Date
        type: datetime
        required: true
      - name: featured
        title: Featured
        type: boolean
        default: false
      - name: draft
        title: Draft
        type: boolean
        default: false
      - name: tags
        title: Tags
        type: list
        field:
          type: string
      - name: description
        title: Description
        type: text
        required: true
      - name: body
        title: Content
        type: markdown
        required: true